name: localization_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  build: ^2.3.0
  http: ^1.2.2
  recase: ^4.1.0
  meta: ^1.15.0
  source_gen: ^1.2.5
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.2.0
  test: ^1.24.0
